/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed": "#281800",
              "inverse-surface": "#31302e",
              "tertiary": "#00442c",
              "inverse-primary": "#94d4b7",
              "surface-container": "#f0edea",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#005236",
              "tertiary-fixed-dim": "#77d9a9",
              "body-charcoal": "#4A4A46",
              "on-secondary-container": "#704b00",
              "on-primary-fixed-variant": "#09513b",
              "surface-variant": "#e5e2de",
              "surface-container-high": "#ebe8e4",
              "background": "#fcf9f5",
              "primary-fixed": "#aff0d2",
              "page-base": "#FAF8F5",
              "on-background": "#1c1c1a",
              "primary-fixed-dim": "#94d4b7",
              "on-primary-container": "#92d2b5",
              "primary-container": "#1a5c45",
              "danger-terracotta": "#C0392B",
              "on-tertiary-container": "#76d8a8",
              "on-surface-variant": "#404944",
              "on-surface": "#1c1c1a",
              "on-error": "#ffffff",
              "on-error-container": "#93000a",
              "on-tertiary-fixed": "#002113",
              "surface-container-highest": "#e5e2de",
              "secondary-fixed": "#ffddaf",
              "outline-variant": "#bfc9c2",
              "secondary-container": "#fdba49",
              "surface-container-low": "#f6f3ef",
              "surface-bright": "#fcf9f5",
              "surface-tint": "#2a6951",
              "on-secondary-fixed-variant": "#614000",
              "tertiary-container": "#005e3e",
              "surface": "#fcf9f5",
              "error": "#ba1a1a",
              "surface-white": "#FFFFFF",
              "on-primary-fixed": "#002115",
              "secondary-fixed-dim": "#fdba49",
              "primary": "#004430",
              "tertiary-fixed": "#93f6c4",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#ffffff",
              "secondary": "#805600",
              "on-tertiary": "#ffffff",
              "surface-dim": "#dcdad6",
              "inverse-on-surface": "#f3f0ec",
              "outline": "#707973",
              "success-sage": "#4CAF82",
              "on-primary": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-mobile": "16px",
              "lg": "40px",
              "gutter": "24px",
              "md": "24px",
              "xs": "8px",
              "xl": "64px",
              "base": "4px",
              "margin-desktop": "48px",
              "sm": "16px"
      },
      "fontFamily": {
              "label-sm": ["DM Sans"],
              "headline-lg": ["Literata"],
              "label-md": ["DM Sans"],
              "display-lg": ["Literata"],
              "body-md": ["DM Sans"],
              "body-lg": ["DM Sans"],
              "body-sm": ["DM Sans"],
              "headline-md": ["Literata"],
              "headline-lg-mobile": ["Literata"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.04em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
